name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "G'day, issues set up broad arcs of activities, if you want to just comment, discuss on discord or put observations into the public wiki"
        pr-message: "Thank you for contributing ... have you claimed your (l)explorer hat?' first pull request"
